ALTER TABLE "StoreOrder"
  ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT NOT NULL DEFAULT 'MERCADOPAGO',
  ADD COLUMN IF NOT EXISTS "cashReceived" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "changeDue" DOUBLE PRECISION;